"""Tests for FlocksHub-bundled tool plugin discovery and install.

Covers the multi-version-tool fix wired through:

* :func:`flocks.hub.catalog._bundled_tool_roots` and
  :func:`flocks.hub.catalog._entry_from_bundled_tool` — bundled tools
  surface in ``list_catalog`` as ``available`` until installed.
* :func:`flocks.hub.installer._resolve_install_destination` — tools
  shipped under ``flockshub/plugins/tools/api/<id>/`` install to
  ``<plugins>/tools/api/<id>/`` so :mod:`flocks.config.api_versioning`
  can still find ``_provider.yaml``.
* :func:`flocks.hub.security.validate_package` — generated bytecode
  caches and VCS metadata are silently skipped instead of failing
  install.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from flocks.hub import catalog, local
from flocks.hub.installer import _resolve_install_destination, install_plugin, uninstall_plugin
from flocks.hub.models import HubPluginManifest
from flocks.hub.security import SKIP_NAMES, validate_package


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def isolated_hub(tmp_path, monkeypatch):
    """Isolated HOME + ``FLOCKS_HUB_ROOT`` pointing at a temp flockshub.

    Each test gets:
    * a private ``$HOME`` so user-level installs land under
      ``$HOME/.flocks/plugins/tools/...``
    * an empty project ``cwd`` so project-level installs don't pollute
      the real repo
    * a fresh ``FLOCKS_HUB_ROOT`` we can populate with bundled fixtures
    """
    home = tmp_path / "home"
    project = tmp_path / "project"
    bundled = tmp_path / "flockshub"
    config = tmp_path / "config"
    data = tmp_path / "data"
    for d in (home, project, bundled, config, data):
        d.mkdir(parents=True)

    monkeypatch.chdir(project)
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("FLOCKS_HUB_ROOT", str(bundled))
    monkeypatch.setenv("FLOCKS_CONFIG_DIR", str(config))
    monkeypatch.setenv("FLOCKS_DATA_DIR", str(data))
    (config / "flocks.json").write_text("{}", encoding="utf-8")

    from flocks.config import api_versioning as versioning
    from flocks.config.config import Config
    from flocks.hub import catalog as hub_catalog
    from flocks.skill.skill import Skill

    def _clear_hub_caches() -> None:
        # ``load_index``/``load_taxonomy``/``_manifest_path_lookup`` are
        # ``@lru_cache``-d on the *real* ``FLOCKS_HUB_ROOT``. If we leave
        # them populated against the test's tmp flockshub, sibling tests
        # in the same session see a phantom (empty) catalog. Reset before
        # AND after to insulate both directions.
        hub_catalog.load_index.cache_clear()
        hub_catalog.load_taxonomy.cache_clear()
        hub_catalog._manifest_path_lookup.cache_clear()

    Config._global_config = None
    Config._cached_config = None
    Skill.clear_cache()
    versioning._reset_descriptor_cache()
    _clear_hub_caches()

    yield {"home": home, "project": project, "bundled": bundled}

    Skill.clear_cache()
    versioning._reset_descriptor_cache()
    _clear_hub_caches()


def _write_bundled_tool(
    bundled_root: Path,
    *,
    plugin_id: str,
    service_id: str,
    version: str,
    group: str = "api",
) -> Path:
    """Drop a minimal valid tool plugin under ``flockshub/plugins/tools/<group>/<id>/``."""
    plugin_dir = bundled_root / "plugins" / "tools" / group / plugin_id
    plugin_dir.mkdir(parents=True)
    (plugin_dir / "_provider.yaml").write_text(
        yaml.safe_dump(
            {
                "name": plugin_id,
                "service_id": service_id,
                "version": version,
                "description": f"{plugin_id} bundled fixture",
            },
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    # One concrete tool definition so _has_direct_tool_payload returns True.
    (plugin_dir / f"{plugin_id}_login.yaml").write_text(
        yaml.safe_dump(
            {
                "name": f"{plugin_id}_login",
                "description": "fixture login tool",
                "provider": service_id,
                "handler": {"type": "http", "method": "POST", "url": "https://example/login"},
                "parameters": [],
            },
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    return plugin_dir


# ---------------------------------------------------------------------------
# _bundled_tool_roots
# ---------------------------------------------------------------------------

class TestBundledToolRoots:
    def test_discovers_api_subdir_plugins(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        roots = catalog._bundled_tool_roots()
        assert ("tool", "onesig_v2_5_3_D20250710") in roots

    def test_skips_group_dirs_themselves(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="foo",
            service_id="foo_api",
            version="1.0",
        )
        roots = catalog._bundled_tool_roots()
        # The ``api/`` directory is a grouping container, not a plugin.
        assert ("tool", "api") not in roots

    def test_skips_dirs_without_payload(self, isolated_hub):
        empty = isolated_hub["bundled"] / "plugins" / "tools" / "api" / "empty"
        empty.mkdir(parents=True)
        # Underscore-prefixed files are ignored by _has_direct_tool_payload,
        # so a dir holding only a provider.yaml-without-tool should not surface.
        (empty / "_provider.yaml").write_text("name: empty\n", encoding="utf-8")
        roots = catalog._bundled_tool_roots()
        assert ("tool", "empty") not in roots

    def test_returns_empty_when_no_bundled_dir(self, isolated_hub, monkeypatch):
        # Point FLOCKS_HUB_ROOT at an empty directory.
        empty_hub = isolated_hub["bundled"].parent / "empty_hub"
        empty_hub.mkdir()
        monkeypatch.setenv("FLOCKS_HUB_ROOT", str(empty_hub))
        assert catalog._bundled_tool_roots() == {}


# ---------------------------------------------------------------------------
# _entry_from_bundled_tool / list_catalog state transitions
# ---------------------------------------------------------------------------

class TestBundledCatalogEntryState:
    def test_bundled_only_lists_as_available(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        entries = catalog.list_catalog(plugin_type="tool")
        match = next((e for e in entries if e.id == "onesig_v2_5_3_D20250710"), None)
        assert match is not None, "bundled tool should appear in catalog"
        assert match.state == "available"
        assert match.installedVersion is None
        assert match.source == "bundled"
        assert match.installPath is None

    def test_installed_bundle_lists_as_installed(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        # Drop a matching local install + record, mirroring what
        # ``install_plugin`` would produce.
        install_dir = (
            isolated_hub["home"]
            / ".flocks"
            / "plugins"
            / "tools"
            / "api"
            / "onesig_v2_5_3_D20250710"
        )
        install_dir.mkdir(parents=True)
        (install_dir / "_provider.yaml").write_text(
            "name: onesig_v2_5_3_D20250710\nservice_id: onesig_api\nversion: '2.5.3 D20250710'\n",
            encoding="utf-8",
        )
        record = local.make_record(
            plugin_type="tool",
            plugin_id="onesig_v2_5_3_D20250710",
            version="2.5.3 D20250710",
            source="bundled:plugins/tools/api/onesig_v2_5_3_D20250710",
            install_path=install_dir,
            enabled=True,
            scope="global",
        )
        local.save_installed_record(record)

        entries = catalog.list_catalog(plugin_type="tool")
        match = next(e for e in entries if e.id == "onesig_v2_5_3_D20250710")
        assert match.state == "installed"
        assert match.installedVersion == "2.5.3 D20250710"


# ---------------------------------------------------------------------------
# Installer destination resolution
# ---------------------------------------------------------------------------

class TestResolveInstallDestination:
    def test_tool_from_bundled_api_preserves_subdir(self, isolated_hub):
        src = _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        dst = _resolve_install_destination("tool", "onesig_v2_5_3_D20250710", src, "global")
        assert dst.parent.name == "api", (
            "tool installs from flockshub api/ must keep the api/ subdir "
            "so api_versioning's _provider.yaml scan still finds them"
        )
        assert dst.name == "onesig_v2_5_3_D20250710"

    def test_tool_from_bundled_python_preserves_subdir(self, isolated_hub):
        src = _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="some_py_tool",
            service_id="py_api",
            version="1.0",
            group="python",
        )
        dst = _resolve_install_destination("tool", "some_py_tool", src, "global")
        assert dst.parent.name == "python"

    def test_non_tool_uses_default_layout(self, isolated_hub):
        # Skill installs go to ``<plugins>/skills/<id>/`` regardless of
        # source layout — no group-prefix preservation.
        src = isolated_hub["bundled"] / "plugins" / "skills" / "demo-skill"
        src.mkdir(parents=True)
        dst = _resolve_install_destination("skill", "demo-skill", src, "global")
        assert dst.parent.name == "skills"
        assert dst.name == "demo-skill"

    def test_tool_from_external_path_uses_default_layout(self, isolated_hub, tmp_path):
        # Source is OUTSIDE flockshub → can't infer a group → fall back
        # to the default ``<plugins>/tools/<id>/`` shape.
        external = tmp_path / "external" / "weird-tool"
        external.mkdir(parents=True)
        dst = _resolve_install_destination("tool", "weird-tool", external, "global")
        assert dst.name == "weird-tool"
        # Default layout: directly under ``tools/`` (no group dir).
        assert dst.parent.name == "tools"


# ---------------------------------------------------------------------------
# End-to-end install / uninstall + multi-version coexistence
# ---------------------------------------------------------------------------

class TestBundledInstallFlow:
    async def test_install_then_uninstall_roundtrip(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )

        record = await install_plugin("tool", "onesig_v2_5_3_D20250710")
        install_path = Path(record.installPath)
        assert install_path.parent.name == "api"
        assert (install_path / "_provider.yaml").is_file()

        # Catalog reflects the install — state flips to ``installed``.
        installed_entries = catalog.list_catalog(plugin_type="tool", state=["installed"])
        assert any(e.id == "onesig_v2_5_3_D20250710" for e in installed_entries)

        removed = await uninstall_plugin("tool", "onesig_v2_5_3_D20250710")
        assert removed is True
        assert not install_path.exists()

        # Back to ``available`` after uninstall — the bundled copy is still
        # on disk in flockshub.
        available_entries = catalog.list_catalog(plugin_type="tool", state=["available"])
        assert any(e.id == "onesig_v2_5_3_D20250710" for e in available_entries)

    async def test_two_versions_install_side_by_side(self, isolated_hub):
        """Different ``service_id`` + same conceptual product can coexist.

        We use distinct ``service_id`` values here because each install
        ID must be unique on disk; the api-versioning layer's
        same-``service_id``-different-version case is covered separately
        in ``tests/config/test_api_versioning.py``.
        """
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_v2_5_3_D20250710_api",
            version="2.5.3 D20250710",
        )
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20260321",
            service_id="onesig_api",
            version="2.5.3 D20260321",
        )

        old = await install_plugin("tool", "onesig_v2_5_3_D20250710")
        new = await install_plugin("tool", "onesig_v2_5_3_D20260321")

        for record in (old, new):
            assert Path(record.installPath).parent.name == "api"
            assert Path(record.installPath).is_dir()

        from flocks.config.api_versioning import discover_api_service_descriptors

        descriptors = {d.storage_key for d in discover_api_service_descriptors(refresh=True)}
        assert "onesig_v2_5_3_D20250710_api_v2_5_3_D20250710" in descriptors
        assert "onesig_api_v2_5_3_D20260321" in descriptors


# ---------------------------------------------------------------------------
# Security validation
# ---------------------------------------------------------------------------

class TestPackageValidationSkipNames:
    def _manifest(self) -> HubPluginManifest:
        return HubPluginManifest.model_validate(
            {
                "schemaVersion": "1.0",
                "id": "demo",
                "type": "tool",
                "name": "demo",
                "description": "demo",
                "version": "1.0.0",
                "category": "integration",
                "source": {"path": "plugins/tools/api/demo"},
            }
        )

    def test_pycache_is_skipped_not_rejected(self, tmp_path):
        package = tmp_path / "demo"
        package.mkdir()
        (package / "_provider.yaml").write_text("name: demo\n", encoding="utf-8")
        cache = package / "__pycache__"
        cache.mkdir()
        (cache / "noise.pyc").write_bytes(b"\x00\x00")

        # Must not raise — historically this rejected the install with
        # "Disallowed path in package: __pycache__".
        validate_package(package, self._manifest())

    def test_skip_names_contains_known_noise(self):
        for name in ("__pycache__", ".git", ".svn", ".DS_Store"):
            assert name in SKIP_NAMES

    def test_path_escape_still_rejected(self, tmp_path):
        package = tmp_path / "demo"
        package.mkdir()
        outside = tmp_path / "outside.txt"
        outside.write_text("hi", encoding="utf-8")
        # Symlink that escapes the package root must still trip the guard.
        (package / "evil").symlink_to(outside)
        with pytest.raises(ValueError, match="escapes"):
            validate_package(package, self._manifest())
