"""Tests for FlocksHub-bundled tool plugin discovery and install.

Covers the multi-version-tool fix wired through:

* :func:`flocks.hub.catalog._bundled_tool_roots` and
  :func:`flocks.hub.catalog._entry_from_bundled_tool` — bundled tools
  surface in ``list_catalog`` as ``available`` until installed.
* :func:`flocks.hub.installer._resolve_install_destination` — tools
  shipped under ``flockshub/plugins/tools/api/<id>/`` install to
  ``<plugins>/tools/api/<id>/`` so :mod:`flocks.config.api_versioning`
  can still find ``_provider.yaml``.
* :func:`flocks.hub.security.validate_package` — generated bytecode
  caches and VCS metadata are silently skipped instead of failing
  install.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from flocks.hub import catalog, local
from flocks.hub.installer import (
    _refresh_runtime,
    _resolve_install_destination,
    install_plugin,
    uninstall_plugin,
)
from flocks.hub.models import HubPluginManifest
from flocks.hub.security import SKIP_NAMES, validate_package


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def isolated_hub(tmp_path, monkeypatch):
    """Isolated HOME + ``FLOCKS_HUB_ROOT`` pointing at a temp flockshub.

    Each test gets:
    * a private ``$HOME`` so user-level installs land under
      ``$HOME/.flocks/plugins/tools/...``
    * an empty project ``cwd`` so project-level installs don't pollute
      the real repo
    * a fresh ``FLOCKS_HUB_ROOT`` we can populate with bundled fixtures
    """
    home = tmp_path / "home"
    project = tmp_path / "project"
    bundled = tmp_path / "flockshub"
    config = tmp_path / "config"
    data = tmp_path / "data"
    for d in (home, project, bundled, config, data):
        d.mkdir(parents=True)

    monkeypatch.chdir(project)
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("FLOCKS_HUB_ROOT", str(bundled))
    monkeypatch.setenv("FLOCKS_CONFIG_DIR", str(config))
    monkeypatch.setenv("FLOCKS_DATA_DIR", str(data))
    (config / "flocks.json").write_text("{}", encoding="utf-8")

    from flocks.config import api_versioning as versioning
    from flocks.config.config import Config
    from flocks.hub import catalog as hub_catalog
    from flocks.skill.skill import Skill

    def _clear_hub_caches() -> None:
        # ``load_index``/``load_taxonomy``/``_manifest_path_lookup`` are
        # ``@lru_cache``-d on the *real* ``FLOCKS_HUB_ROOT``. If we leave
        # them populated against the test's tmp flockshub, sibling tests
        # in the same session see a phantom (empty) catalog. Reset before
        # AND after to insulate both directions.
        hub_catalog.load_index.cache_clear()
        hub_catalog.load_taxonomy.cache_clear()
        hub_catalog._manifest_path_lookup.cache_clear()

    Config._global_config = None
    Config._cached_config = None
    Skill.clear_cache()
    versioning._reset_descriptor_cache()
    _clear_hub_caches()

    yield {"home": home, "project": project, "bundled": bundled}

    Skill.clear_cache()
    versioning._reset_descriptor_cache()
    _clear_hub_caches()


def _write_bundled_tool(
    bundled_root: Path,
    *,
    plugin_id: str,
    service_id: str,
    version: str,
    group: str = "api",
) -> Path:
    """Drop a minimal valid tool plugin under ``flockshub/plugins/tools/<group>/<id>/``."""
    plugin_dir = bundled_root / "plugins" / "tools" / group / plugin_id
    plugin_dir.mkdir(parents=True)
    (plugin_dir / "_provider.yaml").write_text(
        yaml.safe_dump(
            {
                "name": plugin_id,
                "service_id": service_id,
                "version": version,
                "description": f"{plugin_id} bundled fixture",
            },
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    # One concrete tool definition so _has_direct_tool_payload returns True.
    (plugin_dir / f"{plugin_id}_login.yaml").write_text(
        yaml.safe_dump(
            {
                "name": f"{plugin_id}_login",
                "description": "fixture login tool",
                "provider": service_id,
                "handler": {"type": "http", "method": "POST", "url": "https://example/login"},
                "parameters": [],
            },
            allow_unicode=True,
        ),
        encoding="utf-8",
    )
    return plugin_dir


# ---------------------------------------------------------------------------
# _bundled_tool_roots
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_tool_runtime_refresh_clears_device_template_cache(monkeypatch):
    from flocks.config import api_versioning
    from flocks.tool.device import plugin_index
    from flocks.tool.registry import ToolRegistry

    calls: list[str] = []
    monkeypatch.setattr(ToolRegistry, "init", classmethod(lambda cls: calls.append("init")))
    monkeypatch.setattr(
        ToolRegistry,
        "refresh_plugin_tools",
        classmethod(lambda cls: calls.append("refresh")),
    )
    monkeypatch.setattr(
        api_versioning,
        "discover_api_service_descriptors",
        lambda *, refresh=False: calls.append(f"discover:{refresh}") or [],
    )
    plugin_index._template_cache = []

    await _refresh_runtime("device")

    assert plugin_index._template_cache is None
    assert calls == ["init", "refresh", "discover:True"]


class TestBundledToolRoots:
    def test_discovers_api_subdir_plugins(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        roots = catalog._bundled_tool_roots()
        assert ("tool", "onesig_v2_5_3_D20250710") in roots

    def test_skips_group_dirs_themselves(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="foo",
            service_id="foo_api",
            version="1.0",
        )
        roots = catalog._bundled_tool_roots()
        # The ``api/`` directory is a grouping container, not a plugin.
        assert ("tool", "api") not in roots

    def test_skips_dirs_without_payload(self, isolated_hub):
        empty = isolated_hub["bundled"] / "plugins" / "tools" / "api" / "empty"
        empty.mkdir(parents=True)
        # Underscore-prefixed files are ignored by _has_direct_tool_payload,
        # so a dir holding only a provider.yaml-without-tool should not surface.
        (empty / "_provider.yaml").write_text("name: empty\n", encoding="utf-8")
        roots = catalog._bundled_tool_roots()
        assert ("tool", "empty") not in roots

    def test_returns_empty_when_no_bundled_dir(self, isolated_hub, monkeypatch):
        # Point FLOCKS_HUB_ROOT at an empty directory.
        empty_hub = isolated_hub["bundled"].parent / "empty_hub"
        empty_hub.mkdir()
        monkeypatch.setenv("FLOCKS_HUB_ROOT", str(empty_hub))
        assert catalog._bundled_tool_roots() == {}


# ---------------------------------------------------------------------------
# _entry_from_bundled_tool / list_catalog state transitions
# ---------------------------------------------------------------------------

class TestBundledCatalogEntryState:
    def test_bundled_only_lists_as_available(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        entries = catalog.list_catalog(plugin_type="tool")
        match = next((e for e in entries if e.id == "onesig_v2_5_3_D20250710"), None)
        assert match is not None, "bundled tool should appear in catalog"
        assert match.state == "available"
        assert match.installedVersion is None
        assert match.source == "bundled"
        assert match.installPath is None

    def test_installed_bundle_lists_as_installed(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        # Drop a matching local install + record, mirroring what
        # ``install_plugin`` would produce.
        install_dir = (
            isolated_hub["home"]
            / ".flocks"
            / "plugins"
            / "tools"
            / "api"
            / "onesig_v2_5_3_D20250710"
        )
        install_dir.mkdir(parents=True)
        (install_dir / "_provider.yaml").write_text(
            "name: onesig_v2_5_3_D20250710\nservice_id: onesig_api\nversion: '2.5.3 D20250710'\n",
            encoding="utf-8",
        )
        record = local.make_record(
            plugin_type="tool",
            plugin_id="onesig_v2_5_3_D20250710",
            version="2.5.3 D20250710",
            source="bundled:plugins/tools/api/onesig_v2_5_3_D20250710",
            install_path=install_dir,
            enabled=True,
            scope="global",
        )
        local.save_installed_record(record)

        entries = catalog.list_catalog(plugin_type="tool")
        match = next(e for e in entries if e.id == "onesig_v2_5_3_D20250710")
        assert match.state == "installed"
        assert match.installedVersion == "2.5.3 D20250710"


# ---------------------------------------------------------------------------
# Installer destination resolution
# ---------------------------------------------------------------------------

class TestResolveInstallDestination:
    def test_tool_from_bundled_api_preserves_subdir(self, isolated_hub):
        src = _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        dst = _resolve_install_destination("tool", "onesig_v2_5_3_D20250710", src, "global")
        assert dst.parent.name == "api", (
            "tool installs from flockshub api/ must keep the api/ subdir "
            "so api_versioning's _provider.yaml scan still finds them"
        )
        assert dst.name == "onesig_v2_5_3_D20250710"

    def test_tool_from_bundled_python_preserves_subdir(self, isolated_hub):
        src = _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="some_py_tool",
            service_id="py_api",
            version="1.0",
            group="python",
        )
        dst = _resolve_install_destination("tool", "some_py_tool", src, "global")
        assert dst.parent.name == "python"

    def test_non_tool_uses_default_layout(self, isolated_hub):
        # Skill installs go to ``<plugins>/skills/<id>/`` regardless of
        # source layout — no group-prefix preservation.
        src = isolated_hub["bundled"] / "plugins" / "skills" / "demo-skill"
        src.mkdir(parents=True)
        dst = _resolve_install_destination("skill", "demo-skill", src, "global")
        assert dst.parent.name == "skills"
        assert dst.name == "demo-skill"

    def test_tool_from_external_path_without_group_uses_default_layout(self, isolated_hub, tmp_path):
        # Source's parent name (``external``) isn't a recognised group
        # → no prefix to preserve → fall back to ``<plugins>/tools/<id>/``.
        external = tmp_path / "external" / "weird-tool"
        external.mkdir(parents=True)
        dst = _resolve_install_destination("tool", "weird-tool", external, "global")
        assert dst.name == "weird-tool"
        assert dst.parent.name == "tools"

    def test_tool_from_project_level_api_dir_preserves_subdir(self, isolated_hub):
        """Re-installing a project-level API plugin into the user scope must
        also keep the ``api/`` subdir.

        Regression for the case where the FlocksHub catalog surfaces a
        project-level plugin (``<cwd>/.flocks/plugins/tools/api/<id>/``)
        as installable: dropping the group prefix here landed the copy at
        ``~/.flocks/plugins/tools/<id>/`` and silently broke
        ``api_versioning``'s ``_provider.yaml`` discovery.
        """
        src = (
            isolated_hub["project"]
            / ".flocks"
            / "plugins"
            / "tools"
            / "api"
            / "onesig_v2_5_3_D20260321"
        )
        src.mkdir(parents=True)
        (src / "_provider.yaml").write_text(
            "name: onesig\nservice_id: onesig_api\nversion: '2.5.3 D20260321'\n",
            encoding="utf-8",
        )
        dst = _resolve_install_destination("tool", "onesig_v2_5_3_D20260321", src, "global")
        assert dst.parent.name == "api"
        assert dst.name == "onesig_v2_5_3_D20260321"


# ---------------------------------------------------------------------------
# End-to-end install / uninstall + multi-version coexistence
# ---------------------------------------------------------------------------

class TestBundledInstallFlow:
    async def test_install_then_uninstall_roundtrip(self, isolated_hub):
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )

        record = await install_plugin("tool", "onesig_v2_5_3_D20250710")
        install_path = Path(record.installPath)
        assert install_path.parent.name == "api"
        assert (install_path / "_provider.yaml").is_file()

        # Catalog reflects the install — state flips to ``installed``.
        installed_entries = catalog.list_catalog(plugin_type="tool", state=["installed"])
        assert any(e.id == "onesig_v2_5_3_D20250710" for e in installed_entries)

        removed = await uninstall_plugin("tool", "onesig_v2_5_3_D20250710")
        assert removed is True
        assert not install_path.exists()

        # Back to ``available`` after uninstall — the bundled copy is still
        # on disk in flockshub.
        available_entries = catalog.list_catalog(plugin_type="tool", state=["available"])
        assert any(e.id == "onesig_v2_5_3_D20250710" for e in available_entries)

    async def test_uninstall_cleans_orphan_api_service_entry(self, isolated_hub):
        """Flockshub uninstall must drop the bootstrapped api_services
        block too — otherwise the api-services UI would keep showing a
        stale entry pointing at a plugin the user just removed.
        """
        from flocks.config.config_writer import ConfigWriter

        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        await install_plugin("tool", "onesig_v2_5_3_D20250710")

        # Mimic the runtime bootstrap that records the credentials/enabled
        # block keyed on the plugin's storage_key.
        storage_key = "onesig_api_v2_5_3_D20250710"
        ConfigWriter.set_api_service(storage_key, {"enabled": True})
        assert ConfigWriter.get_api_service_raw(storage_key) is not None

        await uninstall_plugin("tool", "onesig_v2_5_3_D20250710")

        assert ConfigWriter.get_api_service_raw(storage_key) is None, (
            "uninstall_plugin should remove the orphaned api_services entry "
            "so the api-services UI doesn't show a phantom service"
        )

    async def test_uninstall_keeps_api_service_when_other_install_still_declares_it(
        self, isolated_hub,
    ):
        """If two installed plugin dirs declare the same storage_key,
        uninstalling one of them must NOT drop the shared
        ``api_services`` entry — the surviving plugin still depends on it.
        """
        from flocks.config.config_writer import ConfigWriter

        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_a",
            service_id="onesig_shared",
            version="2.5.3",
        )
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_b",
            service_id="onesig_shared",
            version="2.5.3",
        )
        await install_plugin("tool", "onesig_a")
        await install_plugin("tool", "onesig_b")

        storage_key = "onesig_shared_v2_5_3"
        ConfigWriter.set_api_service(storage_key, {"enabled": True})

        await uninstall_plugin("tool", "onesig_a")

        assert ConfigWriter.get_api_service_raw(storage_key) is not None, (
            "shared api_services entry must survive when another installed "
            "plugin still declares the same storage_key"
        )

    async def test_two_versions_install_side_by_side(self, isolated_hub):
        """Different ``service_id`` + same conceptual product can coexist.

        We use distinct ``service_id`` values here because each install
        ID must be unique on disk; the api-versioning layer's
        same-``service_id``-different-version case is covered separately
        in ``tests/config/test_api_versioning.py``.
        """
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_v2_5_3_D20250710_api",
            version="2.5.3 D20250710",
        )
        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20260321",
            service_id="onesig_api",
            version="2.5.3 D20260321",
        )

        old = await install_plugin("tool", "onesig_v2_5_3_D20250710")
        new = await install_plugin("tool", "onesig_v2_5_3_D20260321")

        for record in (old, new):
            assert Path(record.installPath).parent.name == "api"
            assert Path(record.installPath).is_dir()

        from flocks.config.api_versioning import discover_api_service_descriptors

        descriptors = {d.storage_key for d in discover_api_service_descriptors(refresh=True)}
        assert "onesig_v2_5_3_D20250710_api_v2_5_3_D20250710" in descriptors
        assert "onesig_api_v2_5_3_D20260321" in descriptors


# ---------------------------------------------------------------------------
# Cascade: delete_api_service → uninstall backing plugin
# ---------------------------------------------------------------------------

class TestDeleteApiServiceCascade:
    """Covers ``delete_api_service`` + ``_find_user_installed_tool_plugin_for``.

    The helper function is the contract: given a storage_key, it must
    return the user-installed plugin id (when one backs it) or ``None``
    otherwise. End-to-end cascade behaviour is exercised by calling
    the route function directly so we don't depend on a live server.
    """

    async def test_finds_user_installed_plugin_by_storage_key(self, isolated_hub):
        from flocks.server.routes.provider import _find_user_installed_tool_plugin_for

        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        await install_plugin("tool", "onesig_v2_5_3_D20250710")

        result = _find_user_installed_tool_plugin_for("onesig_api_v2_5_3_D20250710")
        # ``_find_user_installed_tool_plugin_for`` now returns
        # ``(plugin_type, plugin_id)`` so the delete cascade can route
        # uninstall to the right type (``tool`` or ``device``).
        assert result == ("tool", "onesig_v2_5_3_D20250710")

    async def test_returns_none_when_storage_key_unknown(self, isolated_hub):
        from flocks.server.routes.provider import _find_user_installed_tool_plugin_for
        assert _find_user_installed_tool_plugin_for("nonexistent_v9_9_9") is None

    async def test_finds_user_installed_device_plugin(self, isolated_hub):
        """Devices (``integration_type: device``) should resolve back as
        ``("device", id)`` so the api-service delete cascade uninstalls
        them through the device-typed Hub flow.
        """
        from flocks.server.routes.provider import _find_user_installed_tool_plugin_for

        bundled_plugin = _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="dev_under_device",
            service_id="device_under_test_api",
            version="1.0.0",
            group="device",
        )
        # Mark it as a device plugin via the provider metadata.
        provider_yaml = bundled_plugin / "_provider.yaml"
        provider_yaml.write_text(
            yaml.safe_dump(
                {
                    "name": "dev_under_device",
                    "service_id": "device_under_test_api",
                    "version": "1.0.0",
                    "integration_type": "device",
                    "description": "device fixture",
                },
                allow_unicode=True,
            ),
            encoding="utf-8",
        )

        await install_plugin("device", "dev_under_device")

        result = _find_user_installed_tool_plugin_for("device_under_test_api_v1_0_0")
        assert result == ("device", "dev_under_device")

    async def test_returns_none_for_project_level_plugin(self, isolated_hub, monkeypatch):
        """Project-level plugins (under ``<cwd>/.flocks/plugins/``) are
        NOT considered "user-installed" — we don't want a delete from
        the api-services UI to wipe a project-tracked plugin.
        """
        from flocks.server.routes.provider import _find_user_installed_tool_plugin_for

        project_plugin_dir = (
            isolated_hub["project"] / ".flocks" / "plugins" / "tools" / "api" / "project_tool"
        )
        project_plugin_dir.mkdir(parents=True)
        (project_plugin_dir / "_provider.yaml").write_text(
            "name: project_tool\nservice_id: project_api\nversion: '1.0.0'\n",
            encoding="utf-8",
        )

        from flocks.config import api_versioning as versioning
        versioning._reset_descriptor_cache()

        assert _find_user_installed_tool_plugin_for("project_api_v1_0_0") is None

    async def test_install_refreshes_descriptor_cache(self, isolated_hub):
        """``install_plugin`` must drop ``discover_api_service_descriptors``'
        process-level cache.

        Otherwise the api-services UI's ``_load_provider_yaml_metadata``
        — which reads via the *cached* descriptor list — keeps returning
        ``None`` for the freshly installed plugin until the next process
        restart, leaving its ``version`` / ``name`` blank in the
        ``GET /api/provider/api-services`` response.
        """
        from flocks.config import api_versioning as versioning

        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )

        # Prime the cache with the *empty* set (no plugins installed yet).
        assert versioning.discover_api_service_descriptors() == []

        await install_plugin("tool", "onesig_v2_5_3_D20250710")

        # Without an explicit refresh inside install_plugin, this would
        # still return the empty list from the prior cache hit.
        descriptors = versioning.discover_api_service_descriptors()
        keys = {d.storage_key for d in descriptors}
        assert "onesig_api_v2_5_3_D20250710" in keys

    async def test_delete_api_service_cascades_to_uninstall(self, isolated_hub):
        """End-to-end: deleting the api-service entry should also
        uninstall the backing user-installed plugin so the FlocksHub
        catalog no longer reports it as ``installed``.
        """
        from flocks.config.config_writer import ConfigWriter
        from flocks.server.routes.provider import delete_api_service

        _write_bundled_tool(
            isolated_hub["bundled"],
            plugin_id="onesig_v2_5_3_D20250710",
            service_id="onesig_api",
            version="2.5.3 D20250710",
        )
        record = await install_plugin("tool", "onesig_v2_5_3_D20250710")
        install_path = Path(record.installPath)
        storage_key = "onesig_api_v2_5_3_D20250710"
        ConfigWriter.set_api_service(storage_key, {"enabled": True})

        result = await delete_api_service(storage_key)
        assert result == {"success": True}

        # Plugin gone from disk + records, api-services entry gone too.
        assert not install_path.exists()
        assert ConfigWriter.get_api_service_raw(storage_key) is None

        # Catalog reverts the entry to ``available``.
        entries = catalog.list_catalog(plugin_type="tool", state=["available"])
        assert any(e.id == "onesig_v2_5_3_D20250710" for e in entries)

    async def test_delete_api_service_rejects_project_level_plugin(self, isolated_hub):
        """Project-level API plugins stay protected even without relying on
        the tool registry's in-memory ``native`` flags.
        """
        from fastapi import HTTPException

        from flocks.config import api_versioning as versioning
        from flocks.config.config_writer import ConfigWriter
        from flocks.server.routes.provider import delete_api_service

        project_plugin_dir = (
            isolated_hub["project"] / ".flocks" / "plugins" / "tools" / "api" / "project_tool"
        )
        project_plugin_dir.mkdir(parents=True)
        (project_plugin_dir / "_provider.yaml").write_text(
            yaml.safe_dump(
                {
                    "name": "project_tool",
                    "service_id": "project_api",
                    "version": "1.0.0",
                },
                allow_unicode=True,
            ),
            encoding="utf-8",
        )
        (project_plugin_dir / "project_tool_login.yaml").write_text(
            yaml.safe_dump(
                {
                    "name": "project_tool_login",
                    "description": "fixture login tool",
                    "provider": "project_api",
                    "handler": {
                        "type": "http",
                        "method": "POST",
                        "url": "https://example/login",
                    },
                    "parameters": [],
                },
                allow_unicode=True,
            ),
            encoding="utf-8",
        )
        versioning._reset_descriptor_cache()

        storage_key = "project_api_v1_0_0"
        ConfigWriter.set_api_service(storage_key, {"enabled": True})

        with pytest.raises(HTTPException) as exc_info:
            await delete_api_service(storage_key)

        assert exc_info.value.status_code == 403
        assert ConfigWriter.get_api_service_raw(storage_key) == {"enabled": True}


# ---------------------------------------------------------------------------
# Security validation
# ---------------------------------------------------------------------------

class TestPackageValidationSkipNames:
    def _manifest(self) -> HubPluginManifest:
        return HubPluginManifest.model_validate(
            {
                "schemaVersion": "1.0",
                "id": "demo",
                "type": "tool",
                "name": "demo",
                "description": "demo",
                "version": "1.0.0",
                "category": "integration",
                "source": {"path": "plugins/tools/api/demo"},
            }
        )

    def test_pycache_is_skipped_not_rejected(self, tmp_path):
        package = tmp_path / "demo"
        package.mkdir()
        (package / "_provider.yaml").write_text("name: demo\n", encoding="utf-8")
        cache = package / "__pycache__"
        cache.mkdir()
        (cache / "noise.pyc").write_bytes(b"\x00\x00")

        # Must not raise — historically this rejected the install with
        # "Disallowed path in package: __pycache__".
        validate_package(package, self._manifest())

    def test_skip_names_contains_known_noise(self):
        for name in ("__pycache__", ".git", ".svn", ".DS_Store"):
            assert name in SKIP_NAMES

    def test_path_escape_still_rejected(self, tmp_path):
        package = tmp_path / "demo"
        package.mkdir()
        outside = tmp_path / "outside.txt"
        outside.write_text("hi", encoding="utf-8")
        # Symlink that escapes the package root must still trip the guard.
        (package / "evil").symlink_to(outside)
        with pytest.raises(ValueError, match="escapes"):
            validate_package(package, self._manifest())


# ---------------------------------------------------------------------------
# API-service summary name disambiguation
# ---------------------------------------------------------------------------

class TestDisambiguateSummaryNames:
    """Multi-version siblings need clear labels in the api-services UI.

    The plugin author's ``_provider.yaml`` ``name`` field is what the
    Tools page renders. When two installs of the same product live
    side-by-side under different versions, the user has to be able to
    tell rows apart — otherwise they cannot map a row back to which
    FlocksHub install backs it.
    """

    def _summary(
        self,
        *,
        id: str,
        name: str,
        version: str | None,
        tool_count: int = 0,
    ):
        from flocks.server.routes.provider import APIServiceSummary
        return APIServiceSummary(
            id=id,
            name=name,
            version=version,
            enabled=True,
            status="unknown",
            tool_count=tool_count,
        )

    def test_same_name_siblings_get_version_suffix(self):
        from flocks.server.routes.provider import _disambiguate_summary_names

        items = [
            self._summary(id="onesig_api_v2_5_3_D20260321", name="onesig", version="2.5.3 D20260321"),
            self._summary(id="onesig_api_v2_5_3_D20250710", name="onesig", version="2.5.3 D20250710"),
        ]
        _disambiguate_summary_names(items)

        assert {i.name for i in items} == {
            "onesig (v2.5.3 D20260321)",
            "onesig (v2.5.3 D20250710)",
        }

    def test_same_service_id_family_gets_suffix_even_with_distinct_names(self):
        """Different ``name``s but same ``service_id`` (just versioned
        storage_keys) → user sees consistent ``(v…)`` suffixing on every
        sibling so the family is visually grouped.
        """
        from flocks.server.routes.provider import _disambiguate_summary_names

        items = [
            self._summary(id="onesig_api_v2_5_3_D20260321", name="onesig", version="2.5.3 D20260321"),
            # Same family root (``onesig_api``), different name spelling.
            self._summary(id="onesig_api_v3_0_0", name="onesig-next", version="3.0.0"),
        ]
        _disambiguate_summary_names(items)

        # Both rows now carry the version suffix.
        assert items[0].name == "onesig (v2.5.3 D20260321)"
        assert items[1].name == "onesig-next (v3.0.0)"

    def test_single_version_entry_keeps_short_name(self):
        from flocks.server.routes.provider import _disambiguate_summary_names

        items = [self._summary(id="solo_api_v1_0_0", name="solo", version="1.0.0")]
        _disambiguate_summary_names(items)
        assert items[0].name == "solo"

    def test_name_already_contains_version_is_not_decorated(self):
        """When the plugin author has already baked the version into
        ``name`` (e.g. ``onesig_v2_5_3_D20250710``), don't pile on a
        ``(v2.5.3 D20250710)`` suffix and produce noise.
        """
        from flocks.server.routes.provider import _disambiguate_summary_names

        items = [
            self._summary(
                id="onesig_v2_5_3_D20250710_api_v2_5_3_D20250710",
                name="onesig_v2_5_3_D20250710",
                version="2.5.3 D20250710",
            ),
            self._summary(
                id="onesig_api_v2_5_3_D20260321",
                name="onesig",
                version="2.5.3 D20260321",
            ),
        ]
        _disambiguate_summary_names(items)
        # First name already embeds the version → unchanged.
        assert items[0].name == "onesig_v2_5_3_D20250710"
        # Second is a one-of-its-family entry with a unique name → also unchanged.
        assert items[1].name == "onesig"

    def test_unversioned_entry_is_left_alone(self):
        from flocks.server.routes.provider import _disambiguate_summary_names

        items = [
            self._summary(id="legacy_api", name="legacy", version=None),
            self._summary(id="other_api_v1_0_0", name="other", version="1.0.0"),
        ]
        _disambiguate_summary_names(items)
        assert items[0].name == "legacy"
        assert items[1].name == "other"
